 <?php	
 echo getenv("LD_LIBRARY_PATH");
$conn = odbc_connect('oracle_dsn', 'esmsm_data', 'abc123');
if ($conn) {
    //echo "Oracle ODBC connection successful!";
    //odbc_close($conn);
} else {
    echo "Oracle ODBC connection failed!";
}

$sql = "SELECT
    P.RUJUKAN_KAMI AS RUJUKAN,
    TL.TARIKH_SURAT AS TKH_SURAT,
    to_char (TL.TARIKH_LANTIKAN, 'dd/mm/rrrr') AS TKH_LANTIK, 
    TL.SD_PER_NO_PEMEROLEHAN AS pemerolehan,
    C.NAMA_PENUH AS NAMA,
    C.NO_KP_BARU AS NO_KP,
    C.ALAMAT_1 AS ALAMAT1,
    C.ALAMAT_2 AS ALAMAT2,
    C.ALAMAT_3 AS ALAMAT3,
    C.POSKOD AS POSKOD,
    C.BANDAR AS BANDAR,
    (SELECT DISKRIPSI FROM negeri WHERE KOD=C.TEMPAT_TINGGAL) AS negeri,
    TL.GRED_GAJI_MULA AS GAJI,
    (SELECT GGT.AMAUN FROM gred_gaji_det GGT WHERE  GGT.GGH_KOD = TL.GRED_GAJI_MULA AND GGT.PERINGKAT = TL.PERINGKAT AND GGT.TAHUN = TL.TAHUN) AS AMAUN_MATRIKS,
    (SELECT GGM.GAJI_MINIMUM FROM gred_gaji_min_mak GGM WHERE TL.GRED_GAJI_MULA = GGM.GRED_GAJI AND TL.TAHAP_GAJI_MIN = GGM.TAHAP_GAJI_MIN AND TL.GAJI_MINIMUM = GGM.GAJI_MINIMUM) AS AMAUN_MINMAX,
    TL.SD_SD1_SKI_KOD AS JAWATAN,
    TL.GAJI_MINIMUM AS AMAUN_SB,
    PEG.NAMA AS NAMA_PEGAWAI,
	S.DISKRIPSI AS SKIM,
	SP.DISKRIPSI AS SKIM_PKHIDMAT ,
	SSM.DISKRIPSI AS KUMP_PKHIDMAT,
	K.DISKRIPSI AS KLASIFIKASI
FROM 
    calon C,
    tawaran_lantik TL,
    pemerolehan P,
    pgspa_det det,
    pgspa pg,
    pegawai PEG,
    skim s,
    skim_pkhidmat sp,
    kump_ssm ssm,
    klasifikasi K
WHERE 
    C.NO_PENGENALAN = TL.SD_SD1_CAL_NO_PENGENALAN
	AND TL.SD_PER_NO_PEMEROLEHAN = 'SK20210065'
    AND TL.SD_PER_NO_PEMEROLEHAN = P.NO_PEMEROLEHAN
    AND PEG.KOD = TL.PEG_KOD  
    AND TL.SD_SD1_SKI_KOD = S.KOD
    AND S.SKIM_PKHIDMAT = SP.KOD
    AND S.KUMP_PKHIDMAT_SSB = SSM.KOD
    AND P.NO_PEMEROLEHAN = DET.PER_NO_PEMEROLEHAN
    AND DET.PGS_KOD = PG.KOD
    AND PG.KLA_KOD = K.KOD
	AND C.NO_KP_BARU='970511145111'";

$result = odbc_exec($conn ,$sql);
//print 'ssss'.$result;

if ($result) {
	while($row = odbc_fetch_array($result)){
print $row['RUJUKAN'];
	}

}


//$sql = "INSERT INTO ESMSM_DATA.S_CALON8I (PK_KEY,NO_KELOMPOK,NO_SIRI,LITHO_CODE,JENIS_PENDAFTARAN,NO_KP_BARU,NO_KP_LAMA,SKIM_1,SKIM_2,SKIM_3,SKIM_4,SKIM_5,SKIM_6,SKIM_7,SKIM_8,SKIM_9,SKIM_10,SKIM_11,SKIM_12,SKIM_13,SKIM_14,SKIM_15,SKIM_16,SKIM_17,SKIM_18,SKIM_19,SKIM_20,PUSAT_TD,NAMA_PENUH,TARIKH_LAHIR,TEMPAT_LAHIR,JANTINA,TARAF_PERKAHWINAN,KETURUNAN,AGAMA,KEWARGANEGARAAN,KECACATAN_CALON,DAFTAR_CACAT,NOM_DAFTAR,BIASISWA_P,BANTUAN,NOM_DAFTAR_BANTUAN,TEMPAT_LAHIR_IBU,TEMPAT_LAHIR_BAPA,KOD_TEL,NO_TEL,ALAMAT,ALAMAT2,ALAMAT3,POSKOD,BANDAR,NEGERI_TINGGAL,BAHAGIAN_TINGGAL,TAHUN_SIJIL3,JENIS_SIJIL3,PANGKAT_SIJIL3,MPEL3_1,GRED3_1,MPEL3_2,GRED3_2,MPEL3_3,GRED3_3,MPEL3_4,GRED3_4,MPEL3_5,GRED3_5,MPEL3_6,GRED3_6,MPEL3_7,GRED3_7,MPEL3_8,GRED3_8,MPEL3_9,GRED3_9,MPEL3_10,GRED3_10,TAHUN_SIJIL5,JENIS_SIJIL5,PANGKAT_SIJIL5,UJIAN_LISAN,MPEL5_1,GRED5_1,MPEL5_2,GRED5_2,MPEL5_3,GRED5_3,MPEL5_4,GRED5_4,MPEL5_5,GRED5_5,MPEL5_6,GRED5_6,MPEL5_7,GRED5_7,MPEL5_8,GRED5_8,MPEL5_9,GRED5_9,MPEL5_10,GRED5_10,TAHUN_SIJIL52,JENIS_SIJIL52,PANGKAT_SIJIL52,UJIAN_LISAN52,MPEL52_1,GRED52_1,MPEL52_2,GRED52_2,MPEL52_3,GRED52_3,MPEL52_4,GRED52_4,MPEL52_5,GRED52_5,MPEL52_6,GRED52_6,MPEL52_7,GRED52_7,MPEL52_8,GRED52_8,MPEL52_9,GRED52_9,MPEL52_10,GRED52_10,BM_SAP_TAHUN,BM_SAP_GRED,BM_SAP_LISAN,BM_SETARAF_TAHUN,BM_SETARAF_JENIS,BM_SETARAF_GRED,BM_SETARAF_LISAN,MATH5_TAHUN,MATH5_GRED,TAHUN_SIJIL6_1,JENIS_SIJIL6_1,PANGKAT_SIJIL6_1,MPEL61_1,GRED61_1,MPEL61_2,GRED61_2,MPEL61_3,GRED61_3,MPEL61_4,GRED61_4,MPEL61_5,GRED61_5,TAHUN_SIJIL6_2,JENIS_SIJIL6_2,PANGKAT_SIJIL6_2,MPEL62_1,GRED62_1,MPEL62_2,GRED62_2,MPEL62_3,GRED62_3,MPEL62_4,GRED62_4,MPEL62_5,GRED62_5,BAKAT_1,BAKAT_2,BAKAT_3,JENIS_BAHASA1,PENGUASAAN1,JENIS_BAHASA2,PENGUASAAN2,JENIS_BAHASA3,PENGUASAAN3,KATEGORI,PANGKAT,PENCEN,TARIKH_AHLI,PROFESIONAL,TARIKH_LULUS,JAB_KHAS,TARIKH_LULUS1,CGPA1,INSTITUSI1,P_LAYAK1,KELAYAKAN1,PENGKHUSUSAN1,TARIKH_LULUS2,CGPA2,INSTITUSI2,P_LAYAK2,KELAYAKAN2,PENGKHUSUSAN2,TARIKH_LULUS3,CGPA3,INSTITUSI3,P_LAYAK3,KELAYAKAN3,PENGKHUSUSAN3,JENIS_PERKHIDMATAN,NO_KADP_BARU,NO_KADP_LAMA,TARIKH_LANTIK_1,SKIM_PEKERJAAN,JABATAN,NEGERI_JABATAN,GRED_GAJI,TARAF_JAWATAN,TARIKH_MULA,TARIKH_DISAHKAN,GAJI_BULANAN,PERGERAKAN_GAJI,TARIKH_PEPKHAS,KOD_PEPKHAS,TATATERTIB_1,TKH_HUKUM_1,TATATERTIB_2,TKH_HUKUM_2,HARTA,INDICATOR,JENIS_BORANG,PENGGUNA,TKH_UBAH,LESEN_MEMANDU,INSTITUSI1_FLN,INSTITUSI2_FLN,INSTITUSI3_FLN,SUKAN_1,SUKAN_NAMA_1,SUKAN_PERINGKAT_1,SUKAN_2,SUKAN_NAMA_2,SUKAN_PERINGKAT_2,SUKAN_3,SUKAN_NAMA_3,SUKAN_PERINGKAT_3,PERSATUAN_1,PERSATUAN_NAMA_1,PERSATUAN_JAWATAN_1,PERSATUAN_PERINGKAT_1,PERSATUAN_2,PERSATUAN_NAMA_2,PERSATUAN_JAWATAN_2,PERSATUAN_PERINGKAT_2,PERSATUAN_3,PERSATUAN_NAMA_3,PERSATUAN_JAWATAN_3,PERSATUAN_PERINGKAT_3,SUMBANGAN_REKACIPTA,SUMBANGAN_REKACIPTA_NAMA,SUMBANGAN_REKACIPTA_PERINGKAT,PENCAPAIAN_KHAS,PENCAPAIAN_KHAS_NAMA,PLKN,STATUS_PEKERJAAN,TARIKH_ISYTIHAR_HARTA,ABAI_SEMAK_REKOD,SEBAB_ABAI_SEMAK,TARIKH_ABAI_SEMAK,ID_ABAI_SEMAK,EMAIL,INSTITUSI1_LAIN,INSTITUSI2_LAIN,INSTITUSI3_LAIN,PENGKHUSUSAN1_LAIN,PENGKHUSUSAN2_LAIN,PENGKHUSUSAN3_LAIN,PROFESIONAL_LAIN,SKIM_PEKERJAAN_LAIN,JABATAN_LAIN,PEPKHAS_LAIN,TARIKH_CIPTA,ID_PENCIPTA,JENIS_POHON,FLAG_UPLOAD,TARIKH_UPLOAD,IP_ADDRESS,TAHUN_STAM1,JENIS_STAM1,PANGKAT_STAM1,MPEL_STAM1_1,GRED_STAM1_1,MPEL_STAM1_2,GRED_STAM1_2,MPEL_STAM1_3,GRED_STAM1_3,MPEL_STAM1_4,GRED_STAM1_4,MPEL_STAM1_5,GRED_STAM1_5,MPEL_STAM1_6,GRED_STAM1_6,MPEL_STAM1_7,GRED_STAM1_7,MPEL_STAM1_8,GRED_STAM1_8,MPEL_STAM1_9,GRED_STAM1_9,MPEL_STAM1_10,GRED_STAM1_10,TAHUN_STAM2,MPEL_STAM2_1,GRED_STAM2_1,MPEL_STAM2_2,GRED_STAM2_2,MPEL_STAM2_3,GRED_STAM2_3,MPEL_STAM2_4,GRED_STAM2_4,MPEL_STAM2_5,GRED_STAM2_5,MPEL_STAM2_6,GRED_STAM2_6,MPEL_STAM2_7,GRED_STAM2_7,MPEL_STAM2_8,GRED_STAM2_8,MPEL_STAM2_9,GRED_STAM2_9,MPEL_STAM2_10,GRED_STAM2_10,SUMBER_DAFTAR,JENIS_STAM2,PANGKAT_STAM2,KETINGGIAN,INDICATOR_DESC,KOD_PROGRAM,KOD_OPSYEN,TARIKH_MOHON_JOBSM,TARIKH_MOHON_SPP,TARIKH_KEMASKINI_SPP) 
//VALUES('2973850','2195D879','014',NULL,'03','961225265038',NULL,'3226','3235','2559',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'03','RUHI NASHUHA BINTI NORAZAM','25121996','02','2','1','100','01','1',NULL,'2',NULL,NULL,NULL,NULL,'02','02','018','7901228','NO.6 LINTANG RELAU INDAH 2,','TAMAN RELAU INDAH.',NULL,'14200','BANDAR BAHARU','02',NULL,'2011','1',NULL,'002','A','012','B','021','B','023','C','045','B','050','C','055','C','095','C',NULL,NULL,NULL,NULL,'2013','1',NULL,NULL,'103','1','249','1','511','1','449','4','755','4','756','4','223','3','322','5','765','5',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'01',NULL,NULL,'01','1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,'6','REZA',TIMESTAMP'2022-11-07 12:58:53.0','D',NULL,NULL,NULL,'03','BADMINTON','06','09','BOLA JARING','06',NULL,NULL,NULL,NULL,'KELAB PROSTAR','04','06',NULL,'PERSATUAN BULAN SABIT MERAH MALAYSIA','05','06',NULL,'PERSATUAN PERDAGANGAN','06','06',NULL,NULL,NULL,NULL,NULL,'2',NULL,NULL,NULL,NULL,NULL,NULL,'ruhinasuha@gmail.com',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,TIMESTAMP'2021-08-30 13:23:20.0','JCSADM','5','Y',TIMESTAMP'2022-11-07 12:58:53.0','10.29.25.1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1',NULL,NULL,1.58,'BERSIH DAN DIDAFTAR',NULL,NULL,TIMESTAMP'2021-06-12 19:29:31.0',TIMESTAMP'2021-06-12 19:29:31.0',TIMESTAMP'2021-08-30 13:23:20.0')";

//@session_start();    
//$results = odbc_exec($conn, $sql);
//require_once('connection/adodb.inc.php');
//require_once('connection/common_func.php');

//$conn = odbc_connect('sppdevdb_dsn', 'esmsm_data', 'abc123');
//$conn = ADONEWConnection('odbc');
//$conn->Connect('sppdevdb_dsn', 'esmsm_data', 'abc123', 'sppdevdb');
//exit;
//_pconnect($argDSN, $argUsername, $argPassword, $argDatabasename)
//$results = $conn->query($sql);
 //           if ($results){
   //           echo "Query Executed";
     //       } else {
       //       echo "Query failed " .odbc_errormsg();
         //   }  

//$conn->close();
//odbc_close($conn);
?>
  
